backend:
  name: github
  repo: Uniquebylea/uniquebylea
  branch: main
  base_url: https://uniquebylea.vercel.app
  auth_endpoint: api/auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "shop_data"
    label: "Shop Verwaltung"
    files:
      - label: "Alle Produkte"
        name: "products"
        file: "content/products.json"
        format: "json"
        fields:
          - label: "Produktliste"
            name: "produkte"
            widget: "list"
            collapsed: true
            summary: "{{fields.name}} ({{fields.price}})"
            fields:
              - {label: "Produktname", name: "name", widget: "string"}
              - label: "Kategorie"
                name: "cat"
                widget: "select"
                options: ["Baby", "Kinder", "Erwachsene", "Makramee", "Taschen", "Gutscheine", "Accessoires"]
              - {label: "Preis", name: "price", widget: "string"}
              - label: "Hauptbild (Titelbild)"
                name: "img"
                widget: "image"
              - label: "Weitere Fotos (Detailansichten / Galerie)"
                name: "gallery"
                widget: "list"
                required: false
                field: {label: "Foto", name: "image", widget: "image"}
              - {label: "Stripe Link (Optional)", name: "link", widget: "string", required: false}
